services:
  database:
    image: postgres:16.4-alpine3.20
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      DB_URL: postgres://${DB_USER}:${DB_PASS}@database:5432?sslmode=disable
      JWT_SECRET: ${BE_JWT_SECRET}
    depends_on:
      - database
    ports:
      - ${BE_PORT}:80
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  database:
