services:
  database:
    image: postgres:16.4-alpine3.20
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    restart: unless-stopped

  cache:
    image: redis:7.4.1-alpine3.20
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      DB_URL: postgres://${DB_USER}:${DB_PASS}@database:5432?sslmode=disable
      JWT_SECRET: ${BE_JWT_SECRET}
    depends_on:
      database:
        condition: service_started
      cache:
        condition: service_healthy
    ports:
      - ${BE_PORT}:80
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  database:
